name: "Block Release PR"

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  block-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Block PR (Failing status check)
        run: |
          echo "This PR is blocked. Perform the release to unblock."
          exit 1  # Fail to block the PR
