name: "Block Release PR"

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        options:
          - release-env1
          - release-env2

jobs:
  write-release-trigger:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Fetch latest PR with title "Release to ${{ inputs.environment }}"
        id: find-pr
        uses: actions/github-script@v7
        with:
          script: |
            const response = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              per_page: 1,
            });

            const releasePR = response.data.find(pr => pr.title === `Release to ${{ inputs.environment }}`);
            if (!releasePR) {
              throw new Error(`No PR found with title "Release to ${inputs.environment}"`);
            }

            return { prNumber: releasePR.number };

      - name: Post release trigger comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ steps.find-pr.outputs.result.prNumber }}
          body: |
            🚀 **Ready for Deployment?** 🚀

            Please review all changes before proceeding with the release.
            To trigger the release, simply:

            - [ ] **Check this box to perform the release.**

            Once checked, our automated process will handle the deployment!
