name: "Perform Release on Checkbox Tick"

on:
  issue_comment:
    types: edited

jobs:
  listen-for-release-comment:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    if: contains('github-actions[bot]', github.event.comment.user.login)
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const comment = context.payload.comment.body;
            const checkboxPattern = /(- \[x\] Check this box to perform the release.)/

            // Ensure the comment contains a checked box
            if (!checkboxPattern.test(comment)) {
              throw new Error("Checkbox for release not ticked. Aborting!");
            }

            console.log("Checkbox ticked, proceeding with release...");

      - name: Perform release
        run: |
          echo "Release initiated!"
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

          PR_NUMBER=${{ github.event.issue.number }}
          gh pr merge $PR_NUMBER --squash --admin --delete-branch

          echo "PR #${PR_NUMBER} successfully merged and branch deleted.

      - name: Untick comment
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            const issueNumber = context.issue.number;
            const commentId = context.payload.comment.id;
            const originalComment = context.payload.comment.body;

            // Replace [x] with [ ]
            const updatedComment = originalComment.replace('- [x]', '- [ ]');

            await github.rest.issues.updateComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: commentId,
              body: updatedComment
            });
