name: "Perform Release"

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  issue_comment:
    types: [created]
  pull_request:
    types: [opened]

jobs:
  check-release-comment:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Block unless PR title follows 'Release to' convention or /perform-release comment is made
      - name: Block PR if it is not a release comment on a release pull request
        if: ${{ startsWith(github.event.pull_request.title, 'Release to') == false || github.event_name == 'pull_request' || github.event.comment.body != '/perform-release' }}
        run: |
          echo "Blocking PR merge. Either the PR title does not match the convention or no release comment."
          exit 1  # Block the merge by failing the check

      # Step 2: Detect /perform-release comment and perform the release action
      - name: Perform release action
        if: ${{ github.event.comment.body == '/perform-release' }}
        run: |
          echo "Release approval comment detected. Performing release action..."
          # Add your release logic here
          # Example: Run a script, trigger deployment, etc.
