name: "Perform Release"

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  issue_comment:
    types: [created]

jobs:
  check-for-release-comment:
    if: github.event.issue.pull_request
    runs-on: ubuntu-latest
    permissions:
      checks: write
    steps:
      # Step 1: Checkout the PR branch
      - name: Fetch PR information
        id: pr-info
        run: |
          pr_data=$(gh api -H "Accept: application/vnd.github+json" /repos/${{ github.repository }}/pulls/${{ github.event.issue.number }})

          # Extract ref from the API response
          head_sha=$(echo "$pr_data" | jq -r '.head.sha')
          echo "::set-output name=head_sha::$head_sha"
          echo "Head SHA: $head_sha"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set status check to in progress
        run: |
          gh api -X POST -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/${{ github.repository }}/check-runs \
            -f 'name=Check for Release Comment' \
            -f 'head_sha=${{ steps.pr-info.outputs.head_sha }}' \
            -f 'status=in_progress' \
            -f 'output[title]=Check for Release Comment' \
            -f 'output[summary]=Looking for release comment...'

      - name: Checkout PR Branch using Head SHA
        uses: actions/checkout@v2
        with:
          ref: ${{ steps.pr-info.outputs.head_sha }}

      - name: Check for valid release comment
        if: ${{ !startsWith(github.event.issue.title, 'Release to') || github.event.comment.body != '/perform-release' }}
        run: |
          echo "Blocking PR merge since no valid release comment was found."
          gh api -X POST -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/${{ github.repository }}/check-runs \
            -f 'name=Check for Release Comment' \
            -f 'head_sha=${{ steps.pr-info.outputs.head_sha }}' \
            -f 'status=completed' \
            -f 'conclusion=failure' \
            -f 'output[title]=Check for Release Comment' \
            -f 'output[summary]=Blocking PR merge since no valid release comment was found.'
          exit 1

      # Step 2: Detect /perform-release comment and perform the release action
      - name: Perform release action
        if: ${{ github.event.comment.body == '/perform-release' }}
        run: |
          echo "Release approval comment detected. Performing release action..."
          gh api -X POST -H "Accept: application/vnd.github+json" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              /repos/${{ github.repository }}/check-runs \
              -f 'name=Check for Release Comment' \
              -f 'head_sha=${{ steps.pr-info.outputs.head_sha }}' \
              -f 'status=completed' \
              -f 'conclusion=failure' \
              -f 'output[title]=Check for Release Comment' \
              -f 'output[summary]=Release approval comment detected. Performing release action...'
          exit 0
