name: "Perform Release"

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  issue_comment:
    types: [created]

jobs:
  check-for-release-comment:
    if: github.event.issue.pull_request
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the PR branch
      - name: Fetch PR information
        id: pr-info
        run: |
          pr_data=$(gh api -H "Accept: application/vnd.github+json" /repos/${{ github.repository }}/pulls/${{ github.event.issue.number }})

          # Extract ref from the API response
          pr_ref=$(echo "$pr_data" | jq -r '.base.ref')
          echo "::set-output name=pr_ref::$pr_ref"
          echo "PR Ref: $pr_ref"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout PR Branch
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ steps.pr-info.outputs.pr_ref }}

      - name: Block PR 2
        if: ${{ !startsWith(github.event.issue.title, 'Release to') || github.event.comment.body != '/perform-release' }}
        run: |
          echo "Blocking PR merge 2."
          exit 1 # Block the merge by failing the check

      # Step 2: Detect /perform-release comment and perform the release action
      - name: Perform release action
        if: ${{ github.event.comment.body == '/perform-release' }}
        run: |
          echo "Release approval comment detected. Performing release action..."
          exit 0
